$userObjectId = (Get-AzADUser -UserPrincipalName (Get-AzAccessToken).UserId).Id

Set-Content 'kv-access.tf' 'locals {'
Add-Content 'kv-access.tf' "currentUserId = ""$userObjectId"""
Add-Content 'kv-access.tf' '}'
Add-Content 'kv-access.tf' ''
Add-Content 'kv-access.tf' 'resource "azurerm_key_vault_access_policy" "currentuser" {'
Add-Content 'kv-access.tf' 'key_vault_id = azurerm_key_vault.keyvault_1.id'
Add-Content 'kv-access.tf' 'tenant_id = data.azurerm_client_config.current.tenant_id'
Add-Content 'kv-access.tf' 'object_id = local.currentUserId'
Add-Content 'kv-access.tf' ''
Add-Content 'kv-access.tf' 'key_permissions = ['
Add-Content 'kv-access.tf' '"Get",'
Add-Content 'kv-access.tf' ']'
Add-Content 'kv-access.tf' 'secret_permissions = ['
Add-Content 'kv-access.tf' '"Backup",'
Add-Content 'kv-access.tf' '"Delete",'
Add-Content 'kv-access.tf' '"Get",'
Add-Content 'kv-access.tf' '"list",'
Add-Content 'kv-access.tf' '"purge",'
Add-Content 'kv-access.tf' '"recover",'
Add-Content 'kv-access.tf' '"restore",'
Add-Content 'kv-access.tf' '"set"'
Add-Content 'kv-access.tf' ']'
Add-Content 'kv-access.tf' 'certificate_permissions = ['
Add-Content 'kv-access.tf' '"Backup",'
Add-Content 'kv-access.tf' '"Create",'
Add-Content 'kv-access.tf' '"Delete",'
Add-Content 'kv-access.tf' '"DeleteIssuers",'
Add-Content 'kv-access.tf' '"Get",'
Add-Content 'kv-access.tf' '"GetIssuers",'
Add-Content 'kv-access.tf' '"Import",'
Add-Content 'kv-access.tf' '"List",'
Add-Content 'kv-access.tf' '"ListIssuers",'
Add-Content 'kv-access.tf' '"ManageContacts",'
Add-Content 'kv-access.tf' '"ManageIssuers",'
Add-Content 'kv-access.tf' '"Purge",'
Add-Content 'kv-access.tf' '"Recover",'
Add-Content 'kv-access.tf' '"Restore",'
Add-Content 'kv-access.tf' '"SetIssuers",'
Add-Content 'kv-access.tf' '"Update"'
Add-Content 'kv-access.tf' ']'
Add-Content 'kv-access.tf' '}'

